### ISSUE TITLE
Daylight saving time bug / Sommerzeit-Bug

### ISSUE THREAD

**Issue by pgerstbach** [sp4c38/AWattPrice#67]
It seems there is a daylight saving time bug in the application.
Yesterday (30.10.) it showed the hour 2-3h of today (31.10.) correctly 2x times.
But today the 10-11 bar is shown, although it is already past 11:00.

Here is a screenshot from today for region "Austria":

![awattprice](https://user-images.githubusercontent.com/10688467/139578427-d153504f-b45c-4fcd-a2f3-44f878b0b253.jpeg)

It seems Awattar has a bug there as well, but they show the caption of x-axis in the wrong way.
![awattar](https://user-images.githubusercontent.com/10688467/139578331-a8fc6742-a6bf-4d84-bfea-81d16673ff6f.png)

I suspect your dates are correct, but the 10h bar should not be visible.
Here are EPEX prices: https://www.epexspot.com/en/market-data?market_area=AT&trading_date=2021-10-30&delivery_date=2021-10-31&underlying_year=&modality=Auction&sub_modality=DayAhead&product=60&data_mode=table&period=

**Comment by sp4c38** [comment]
Thank you for your bug report 👍. That definitely an issue which I didn't consider when programming this part of the App. I will take a closer look the next few days.
I also just checked the aWATTar website for Germany. It can't tell why but they don't seem to render the graphs in AT the same as in DE. The german aWATTar website delivers two bars for the hour 2 to 3 with correct times.

<img width="2958" alt="image" src="https://user-images.githubusercontent.com/36799235/139601949-96944b71-de66-440f-be24-379230a500ab.png">

This issue shouldn't be present anymore from tomorrow on. I will leave this issue open until the bug is fixed, so that it doesn't show the last hour although it isn't the current hour. Its good to fix this issue for future daylight saving switches.

**Comment by pgerstbach** [comment]
Well, thank you for your awesome app, I use it almost every day!
I noticed as well that awattar is using different visualisation for the German market, very strange indeed...

**Comment by sp4c38** [comment]
Thanks, glad you like it.

**Comment by sp4c38** [comment]
I just submitted an update to Apple for solving this bug.
Summer time to normal time had already been fixed, but it didn't do it for normal time to summer time. It actually shows one bar too few today.
As soon as the update gets accepted, these two issues should be fixed. Thanks again for the report.
